### ISSUE TITLE
Thanks for sharing the code!

### ISSUE THREAD

**Issue by philips** [stuffbyrae/first-in-line#1]
I wanted to thank you for sharing the code to your game. It is helpful to have more examples of games for Playdate and how they are constructed when learning.

That said do you think you could put a LICENSE on this file? I wanted to borrow some code like the scene manager but don't want to take something that you don't want copied. Thanks!

**Comment by raewtf** [comment]
here we go, code is* under the MIT license now! thanks for the reminder hahah

though i would say gimme a couple days to make another push before you take a read at that scene manager code — i learned from another project that i beliiieve the current implementation has some issues with sprites not being properly removed from memory; i have a tweak that i believe fixes it but i just need to implement it in here as well

**Comment by philips** [comment]
Cool thanks! My kid (6yo) and I love the game. Just bought the upgraded version on the catalog!

**Comment by raewtf** [comment]
forgot to mention but i pushed the code for 2.2.0 a couple days ago so the code should be a bit more kosher! gonna close this issue up now, but let me know if you need help with anything else
